# Install dependencies only when needed
FROM node:20-alpine3.17 AS deps
WORKDIR /usr/src/app
COPY ./dist/apps/hulaak/package.json ./
RUN npm install -g pnpm && pnpm install

FROM node:20-alpine3.17 AS builder
WORKDIR /usr/src/app
COPY ./dist/apps/hulaak/ ./
COPY --from=deps /usr/src/app/node_modules ./node_modules
RUN npm install -g pnpm && pnpx prisma generate
CMD [ "node", "main.js" ]